spring:
  profiles:
    default: dev
  jackson:
    time-zone: Asia/Seoul
  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
