spring:
  datasource:
    url: jdbc:mysql://localhost:3307/roccia?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

cors:
  allowed-origin-patterns: http://localhost:*,http://127.0.0.1:*,http://[::1]:*

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
